// GENERATED by convex-localfirst codegen. Do not edit by hand.
import { defineLocalFirstManifest, localTable } from "@convex-localfirst/core";
// Manifest interpreters are internal (I13 — they stay off the
// public surface); generated code is a legitimate internal consumer of them.
import {
  declarativeInsert,
  declarativePatch,
  declarativeQuery,
  declarativeRemove
} from "@convex-localfirst/core/internal";

export const localFirstManifest = defineLocalFirstManifest({
  schemaVersion: 1,
  tables: {
    "comments": localTable({"table":"comments","idField":"localId","scope":{"kind":"byWorkspace","workspaceIdField":"workspaceId","membershipTable":"ws_members"},"conflict":"fieldLww","indexes":{"byWorkspace":["workspaceId","createdAt"]}}),
    "doc_updates": localTable({"table":"doc_updates","idField":"localId","scope":{"kind":"byWorkspace","workspaceIdField":"workspaceId","membershipTable":"ws_members"},"conflict":"fieldLww","indexes":{"byWorkspace":["workspaceId","createdAt"],"byDoc":["workspaceId","docId","createdAt"]}}),
    "documents": localTable({"table":"documents","idField":"localId","scope":{"kind":"byWorkspace","workspaceIdField":"workspaceId","membershipTable":"ws_members"},"conflict":"fieldLww","indexes":{"byWorkspace":["workspaceId","position"]}}),
    "issues": localTable({"table":"issues","idField":"localId","scope":{"kind":"byWorkspace","workspaceIdField":"workspaceId","membershipTable":"ws_members"},"conflict":"fieldLww","indexes":{"byWorkspace":["workspaceId","createdAt"]}}),
    "labels": localTable({"table":"labels","idField":"localId","scope":{"kind":"byWorkspace","workspaceIdField":"workspaceId","membershipTable":"ws_members"},"conflict":"fieldLww","indexes":{"byWorkspace":["workspaceId","name"]}}),
    "issue_labels": localTable({"table":"issue_labels","idField":"localId","scope":{"kind":"byWorkspace","workspaceIdField":"workspaceId","membershipTable":"ws_members"},"conflict":"fieldLww","indexes":{"byWorkspace":["workspaceId","issueId"]}}),
    "projects": localTable({"table":"projects","idField":"localId","scope":{"kind":"byWorkspace","workspaceIdField":"workspaceId","membershipTable":"ws_members"},"conflict":"fieldLww","indexes":{"byWorkspace":["workspaceId","createdAt"]}}),
    "todos": localTable({"table":"todos","idField":"localId","scope":{"kind":"byUser","field":"ownerId"},"conflict":"fieldLww","indexes":{"byList":["ownerId","listId","createdAt"]}})
  },
  queries: {
    "issues:list": declarativeQuery({"name":"issues:list","table":"issues","filters":["workspaceId"],"orderBy":"createdAt","order":"asc","initial":[],"scope":{"kind":"byWorkspace","valueArg":"workspaceId"}}),
    "todos:list": declarativeQuery({"name":"todos:list","table":"todos","filters":["listId"],"orderBy":"createdAt","order":"asc","initial":[]})
  },
  mutations: {
    "comments:add": declarativeInsert({"name":"comments:add","table":"comments","fields":{"workspaceId":{"from":"arg","arg":"workspaceId"},"issueId":{"from":"arg","arg":"issueId"},"author":{"from":"arg","arg":"author"},"body":{"from":"arg","arg":"body"},"createdAt":{"from":"now"}}}),
    "comments:remove": declarativeRemove({"name":"comments:remove","table":"comments","idArg":"id"}),
    "docUpdates:append": declarativeInsert({"name":"docUpdates:append","table":"doc_updates","fields":{"workspaceId":{"from":"arg","arg":"workspaceId"},"docId":{"from":"arg","arg":"docId"},"update":{"from":"arg","arg":"update"},"createdAt":{"from":"now"}}}),
    "docUpdates:prune": declarativeRemove({"name":"docUpdates:prune","table":"doc_updates","idArg":"id"}),
    "documents:create": declarativeInsert({"name":"documents:create","table":"documents","fields":{"workspaceId":{"from":"arg","arg":"workspaceId"},"title":{"from":"arg","arg":"title"},"icon":{"from":"arg","arg":"icon"},"parentId":{"from":"arg","arg":"parentId"},"position":{"from":"arg","arg":"position"},"createdAt":{"from":"now"},"updatedAt":{"from":"now"}}}),
    "documents:remove": declarativeRemove({"name":"documents:remove","table":"documents","idArg":"id"}),
    "documents:rename": declarativePatch({"name":"documents:rename","table":"documents","idArg":"id","fields":{"title":{"from":"arg","arg":"title"},"updatedAt":{"from":"now"}}}),
    "documents:setIcon": declarativePatch({"name":"documents:setIcon","table":"documents","idArg":"id","fields":{"icon":{"from":"arg","arg":"icon"},"updatedAt":{"from":"now"}}}),
    "issues:create": declarativeInsert({"name":"issues:create","table":"issues","fields":{"workspaceId":{"from":"arg","arg":"workspaceId"},"projectId":{"from":"arg","arg":"projectId"},"title":{"from":"arg","arg":"title"},"status":{"from":"const","value":"backlog"},"priority":{"from":"arg","arg":"priority"},"assignee":{"from":"arg","arg":"assignee"},"createdAt":{"from":"now"},"updatedAt":{"from":"now"}}}),
    "issues:remove": declarativeRemove({"name":"issues:remove","table":"issues","idArg":"id"}),
    "issues:setPriority": declarativePatch({"name":"issues:setPriority","table":"issues","idArg":"id","fields":{"priority":{"from":"arg","arg":"priority"},"updatedAt":{"from":"now"}}}),
    "issues:setStatus": declarativePatch({"name":"issues:setStatus","table":"issues","idArg":"id","fields":{"status":{"from":"arg","arg":"status"},"updatedAt":{"from":"now"}}}),
    "labels:create": declarativeInsert({"name":"labels:create","table":"labels","fields":{"workspaceId":{"from":"arg","arg":"workspaceId"},"name":{"from":"arg","arg":"name"},"color":{"from":"arg","arg":"color"}}}),
    "labels:link": declarativeInsert({"name":"labels:link","table":"issue_labels","fields":{"workspaceId":{"from":"arg","arg":"workspaceId"},"issueId":{"from":"arg","arg":"issueId"},"labelId":{"from":"arg","arg":"labelId"}}}),
    "labels:unlink": declarativeRemove({"name":"labels:unlink","table":"issue_labels","idArg":"id"}),
    "projects:create": declarativeInsert({"name":"projects:create","table":"projects","fields":{"workspaceId":{"from":"arg","arg":"workspaceId"},"name":{"from":"arg","arg":"name"},"color":{"from":"arg","arg":"color"},"createdAt":{"from":"now"}}}),
    "todos:create": declarativeInsert({"name":"todos:create","table":"todos","fields":{"ownerId":{"from":"auth"},"listId":{"from":"arg","arg":"listId"},"text":{"from":"arg","arg":"text"},"done":{"from":"const","value":false},"createdAt":{"from":"now"},"updatedAt":{"from":"now"}}}),
    "todos:remove": declarativeRemove({"name":"todos:remove","table":"todos","idArg":"id"}),
    "todos:toggle": declarativePatch({"name":"todos:toggle","table":"todos","idArg":"id","fields":{"done":{"from":"arg","arg":"done"},"updatedAt":{"from":"now"}}})
  }
});
